project:
  type: website
  output-dir: docs

website:
  title: "Clinical Reporting Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/istaloni/ClinicalReportingBlog

format:
  html:
    theme: cosmo
