project:
  type: website
  output-dir: docs

website:
  title: "Clinical Reporting Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/istaloni/ClinicalReportingBlog

format:
  html:
    theme: cosmo
